version: '3'
services:
    screeps:
        image: screepers/screeps-launcher
        volumes:
            - ./config.yml:/screeps/config.yml
            - screeps-data:/screeps
        ports:
            - 21025:21025/tcp
        restart: unless-stopped
volumes:
    screeps-data:
